### ISSUE TITLE
Navigation failed because browser has disconnected

### ISSUE THREAD

**Issue by dhruven08** [shelfio/chrome-aws-lambda-layer#17]
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Navigation failed because browser has disconnected!",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Navigation failed because browser has disconnected!",
        "stack": [
            "Error: Navigation failed because browser has disconnected!",
            "    at CDPSession.<anonymous> (/var/task/node_modules/puppeteer-core/lib/LifecycleWatcher.js:46:107)",
            "    at CDPSession.emit (events.js:311:20)",
            "    at CDPSession.EventEmitter.emit (domain.js:482:12)",
            "    at CDPSession._onClosed (/var/task/node_modules/puppeteer-core/lib/Connection.js:215:10)",
            "    at Connection._onMessage (/var/task/node_modules/puppeteer-core/lib/Connection.js:105:17)",
            "    at WebSocket.<anonymous> (/var/task/node_modules/puppeteer-core/lib/WebSocketTransport.js:44:24)",
            "    at WebSocket.onMessage (/var/task/node_modules/ws/lib/event-target.js:120:16)",
            "    at WebSocket.emit (events.js:311:20)",
            "    at WebSocket.EventEmitter.emit (domain.js:482:12)",
            "    at Receiver.receiverOnMessage (/var/task/node_modules/ws/lib/websocket.js:789:20)",
            "  -- ASYNC --",
            "    at Frame.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:111:15)",
            "    at Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:675:49)",
            "    at Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:112:23)",
            "    at _downloadFile (/var/task/index.js:158:10)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
            "    at async /var/task/index.js:74:13"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Navigation failed because browser has disconnected!",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:311:20)",
        "    at process.EventEmitter.emit (domain.js:482:12)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}

**Comment by vladgolubev** [comment]
Stale issue
