### ISSUE TITLE
chrome-aws-lambda layer available for Python Language??

### ISSUE THREAD

**Issue by mgsaranraj87** [shelfio/chrome-aws-lambda-layer#18]
Hi Team,

Can you help me getting the chrome version for python language to be used in AWS Lambda or you can guide me to right place where i can find chrome for python.

**Comment by dgallitelli** [comment]
Having a working version for Python would be definitely amazing.

**Comment by vladgolubev** [comment]
I cannot do this as I don't know nor use Python in my job.

But PRs are welcome!
