### ISSUE TITLE
Permission Error When Attempting to Use Layer

### ISSUE THREAD

**Issue by pacarvalho** [shelfio/chrome-aws-lambda-layer#19]
I am using AWS SAM to deploy a Lambda using this Layer. I have added the following specification for the layer in my YAML:
```yaml
Layers:
  - arn:aws:lambda:us-west-1:764866452798:layer:chrome-aws-lambda:18
```

However, when attempting to deploy (or debug locally) I get the following error: "Error: Credentials provided are missing lambda:Getlayerversion policy that is needed to download the layer or you do not have permission to download the layer"

Where should this permission be added?

**Comment by vladgolubev** [comment]
Hey @pacarvalho 

Please try version 16. Version 18 is in `us-east-1` region only

![image](https://user-images.githubusercontent.com/3817380/89189229-5f668e00-d5a8-11ea-8e4b-cecf9ed03939.png)

**Comment by pacarvalho** [comment]
@vladgolubev Thank you for the fast reply! That was the issue. Thank you :)
