### ISSUE TITLE
Space before "From" field for pdf that was result of conversion from html that was converted from email file

### ISSUE THREAD

**Issue by LLDmitry** [shelfio/chrome-aws-lambda-layer#23]
We have a chain of conversion: msg to html (by GleamTech) ; html-to pdf (by chrome-aws-layer). Html is identical to msg, but in pdf we get empty space before the "From" field (the first row)

**Comment by vladgolubev** [comment]
This layer just embeds the Chrome.

If you got some weird formatting problem, it will most likely be reproduced locally with Chrome on your laptop.

Most likely it's fixed by custom CSS overrides or some Chrome settings you can look up within puppeteer docs.
