### ISSUE TITLE
Publish lambda layer to Africa (af-south-1) region

### ISSUE THREAD

**Issue by jojinkb** [shelfio/chrome-aws-lambda-layer#27]
It would be great if the layer was made available in more regions like Africa.

**Comment by vladgolubev** [comment]
Previously I couldn't publish to that region b/c it didn't support S3 multi-part uploads

see this commit message https://github.com/shelfio/chrome-aws-lambda-layer/commit/c2e190bd9cf0cfef490e15064200febeefd9b7e4

feel free to reopen the issue if you have a proof that it will work now
