### ISSUE TITLE
page.waitForTimeout

### ISSUE THREAD

**Issue by santiago-flores-kenility** [shelfio/chrome-aws-lambda-layer#28]
await page.goto(body.url);
await page.waitForTimeout(5000);

fails with:
{
    "errorType": "TypeError",
    "errorMessage": "page.waitForTimeout is not a function",
    "stack": [
        "TypeError: page.waitForTimeout is not a function",
        "    at Runtime.exports.handler (/var/task/src/testing.js:31:14)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}

How can I set the timeout? Is there any other options?

Thank you

**Comment by rlecaro2** [comment]
Be sure to be using the layer that has Puppeteer v.5.3.0 or greater since [that version is the one that introduces waitForTimeout](https://github.com/puppeteer/puppeteer/releases/tag/v5.3.0).

The deprecated method is using `waitFor`.

**Comment by vladgolubev** [comment]
Yeap, and now the version is 14.3.0 🙂
