### ISSUE TITLE
Cannot find module 'iltorb' on lambda with nodejs10.x

### ISSUE THREAD

**Issue by GabrielJimenezV** [shelfio/chrome-aws-lambda-layer#3]
Cannot find module 'iltorb' error when the runtime is nodejs10.x

**Comment by vladgolubev** [comment]
Hey @GabrielJimenezV 

Is this by chance the same issue you're having? https://github.com/shelfio/aws-lambda-libreoffice/issues/98

**Comment by GabrielJimenezV** [comment]
Yes, sorry for the delay on the response and thanks.

**Comment by alixaxel** [comment]
FYI the `nodejs10.x` runtime is now using Node 10.16, which has native Brotli support.

**Comment by vladgolubev** [comment]
Hey @GabrielJimenezV 

I've just published a new layer version which works on Node 10

Check out new ARNs in [readme](https://github.com/shelfio/chrome-aws-lambda-layer#available-regions)
