### ISSUE TITLE
Function doesnt work when invoked with API Gateway

### ISSUE THREAD

**Issue by francisacosta** [shelfio/chrome-aws-lambda-layer#32]
Hi, has anyone encountered the puppeteer doesnt work when lambda function is called with API Gateway? its works fine when run on lambda function code editor. I notice that it stops working when its starting to work on a pop-up modal.

**Comment by vladgolubev** [comment]
This is most likely a problem with your code, not the layer. The layer doesn't care is there an API gateway or whatever in front of Lambda.
