### ISSUE TITLE
Can this layer be used with Python?

### ISSUE THREAD

**Issue by boeschl** [shelfio/chrome-aws-lambda-layer#41]
IF this layer could be used with Python, What should be the path to include in selenium to the location of Chromium?

**Comment by vladgolubev** [comment]
This should hint an answer: https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.ts#L152-L157

**Comment by vladgolubev** [comment]
See the answer at https://github.com/shelfio/chrome-aws-lambda-layer/issues/18
