### ISSUE TITLE
Update to Chrome ≥ 103

### ISSUE THREAD

**Issue by jandppw** [shelfio/chrome-aws-lambda-layer#43]
This is a very nice service to the community. Thank you shelfio.

We have been waiting for updates for a while now.

This package 

* depends on [`chrome-aws-lambda`](https://github.com/alixaxel/chrome-aws-lambda), which itself 
* depends on [`puppeteer`](https://www.npmjs.com/package/puppeteer) / [`puppeteer-core`](https://www.npmjs.com/package/puppeteer-core), which depends on 
* [`chromium`](https://www.chromium.org/)

The latter 2 evolve continuously. [`puppeteer`](https://www.npmjs.com/package/puppeteer) / [`puppeteer-core`](https://www.npmjs.com/package/puppeteer-core) is currently at [`14.3.0`](https://www.npmjs.com/package/puppeteer-core/v/14.3.0), and offers `Chromium 103.0.5059.0 (r1002410)`.

[`chrome-aws-lambda`](https://github.com/alixaxel/chrome-aws-lambda) is stuck at [`10.1.0`](https://www.npmjs.com/package/puppeteer-core/v/10.1.0), due to build problems. [PRs](https://github.com/alixaxel/chrome-aws-lambda/pull/264) are not responded to.

[@sparticuz](https://www.npmjs.com/package/@sparticuz/chrome-aws-lambda) seems to have picked up the slack.

Maybe this service should switch to that fork as dependency, and move on? Or should we consider this service defunct too?

Are there alternatives that are more up-to-date? Can we assist?

**Comment by vladgolubev** [comment]
Wow, thanks for pointing out the https://www.npmjs.com/package/@sparticuz/chrome-aws-lambda ! I wasn't aware of the new fork.

I'll try to update the layer with the fork.

**Comment by vladgolubev** [comment]
I've just published [a new layer version 27 ](https://github.com/shelfio/chrome-aws-lambda-layer/compare/54583aef840ac1a0a3a2574e41ee65f418a1796e...80dfaa1ef6b23fbd343c831b2c5f670675e7f8d7)that is based on that fork with the latest Chromium and Node 16 support!

Thanks again for pointing this out!
