### ISSUE TITLE
Lambda layers publish by shelf no longer working? 

### ISSUE THREAD

**Issue by andreverheij** [shelfio/chrome-aws-lambda-layer#46]
Hi Team, 

have been using your great lambda Layer to generate PDF's in a Lambda, but now deploying a new lambda with the same code and version of the layer etc and get error "Cannot find module 'chrome-aws-lambda' " 

currently deployed Lambda's are working, just not new ones it seems. Are you no longer providing this shared layer? 

Regards, Andre

**Comment by chrisbloe** [comment]
Thanks for this... Please could you add a note to [readme.md](https://github.com/shelfio/chrome-aws-lambda-layer/blob/master/readme.md)? I think a lot of people will be caught out by this!

**Comment by vladgolubev** [comment]
done!

![CleanShot 2022-07-28 at 19 20 44@2x](https://user-images.githubusercontent.com/3817380/181599014-901c8d05-57f8-4172-a688-4b9a7a83f196.png)
