### ISSUE TITLE
[Documentation Request]: Mark layer as only x86_64 compatible

### ISSUE THREAD

**Issue by LukaHedt** [shelfio/chrome-aws-lambda-layer#48]
Hi,

Sorry to be a pest, but I've been messing about all day with this and have only just realised that the layer is only x86 compatible, not ARM compatible.

Would appreciate that being marked somewhere in the docs :')

FYI for the next poor person using this layer, and maybe not familiar with lambda layers, here's the settings you want:

**package.json**
- `@sparticuz/chrome-aws-lambda` marked as a dependency
- `puppeteer-core` marked as a dependency

**lambda container settings**:
- x86_64 architecture
- >=512mb memory
- `@sparticuz/chrome-aws-lambda` marked as an externalModule in the bundling settings
- A lambda layer marked like so (this is CDK code, but convert to SAM or whatever at will):
```ts
layers: [
                    LayerVersion.fromLayerVersionArn(
                        this,
                        'chromium-lambda-layer',
                        'arn:aws:lambda:ap-southeast-2:764866452798:layer:chrome-aws-lambda:31'
                    ),
                ],
```

**In the deployed lambda code**
You can just use a regular ES6 or CommonJS import statement for `@sparticuz/chrome-aws-lambda`, and just use as indicated.

Just a note, I don't have it currently resolving properly, locally, with Jest, it throws some prototyping error when trying to resolve puppeteer.

**Comment by vladgolubev** [comment]
Thanks! Version 33 is now marked as `--compatible-architectures x86_64`

**Comment by vladgolubev** [comment]
![2023-09-14T11 09 24-AME8yYsI@2x](https://github.com/shelfio/chrome-aws-lambda-layer/assets/3817380/90954805-f5bf-4ba7-8a92-0edaa43cd368)

**Comment by vladgolubev** [comment]
![2023-09-14T11 12 36-MiCBk9KD@2x](https://github.com/shelfio/chrome-aws-lambda-layer/assets/3817380/d3dc022f-17be-4f37-8b99-490141d12528)
