### ISSUE TITLE
path to chromium executable? 

### ISSUE THREAD

**Issue by jeffehobbs** [shelfio/chrome-aws-lambda-layer#51]
I'm using this layer in the context of pyppeteer and things are a bit different there. What's the absolute path to the chromium binary while using this layer?

**Comment by starkos** [comment]
There actually isn't one at first. When the include Node module's `chromium.executablePath()` is called the required files are decompressed and placed into `/tmp`. After that, the path will be `/tmp/chromium`. If you want to access this from something other than NodeJs you'll have to replicate that behavior (I'm currently considering jumping through these hoops with Java).

**Comment by jeffehobbs** [comment]
Thanks, this makes sense. Maybe I'll try to reverse engineer that function for python. Thanks for the tip!
