### ISSUE TITLE
Why not implementing an automatic grab release pattern?

### ISSUE THREAD

**Issue by iwaduarte** [shelfio/chrome-aws-lambda-layer#57]
From what I could get this repo is manually updated and falls behind (like it should) from the main chromium-lambda source.

Why not make it automatic?

**Comment by vladgolubev** [comment]
Well, there are many patterns not implemented here. One has only so much time. But PRs are definitely welcome!

**Comment by iwaduarte** [comment]
I will be dropping something this week

**Comment by iwaduarte** [comment]
https://github.com/shelfio/chrome-aws-lambda-layer/pull/59
